### ISSUE TITLE
Cloud - Modification extension

### ISSUE THREAD

**Issue by 14280** [xsecrecy/bugs#26]
Dans Cloud:
Quand on modifie le nom d'un fichier, si on supprime son extension, ou on le change, le fichier, apparait dans l'overview comme changer aussi. (Exemple: J'ai supprimé le ".pdf" à la fin de mon fichier en le renommant, et du coup, il est passé d'un fichier pdf à un fichier lambda et quand je le télécharge, il est en ".txt")

Sur n'importe quel explorer comme windows cela agit pareil. Il y a juste une popup qui previens si on veux vraiment changer l'extension

**Comment by Achaak** [comment]
C'est dev
